export type Proyecto = {
  name: string;
  folder: string;
  subfolder?: string;
  location?: string;
  year?: string;
  type?: string;
  description?: string;
};

export const proyectosMap: Record<string, Proyecto> = {
  // ── 02 ─────────────────────────────────────────────────────────────────────
  "margo": {
    name: "Margo",
    folder: "02 margo",
    location: "Santiago",
    year: "2019",
    type: "Restaurante",
    description: "Un interior que mira hacia adentro y hacia arriba. El jardín de Margo crece entre vigas y cristales, llevando la naturaleza al corazón del espacio gastronómico. Olivos, muros vegetales y árboles de interior crean un ambiente donde comer es también conectarse con lo vivo.",
  },
  "bertin": {
    name: "Bertin",
    folder: "02 bertin",
    location: "Santiago",
    year: "2018",
    type: "Residencial",
    description: "Un jardín diseñado para una familia que busca vivir el exterior como extensión del hogar. Espacios delimitados por vegetación, terrazas que se abren al verde y una paleta de plantas que cambia con las estaciones.",
  },
  "andrea-bertin-playa": {
    name: "Andrea Bertin Playa",
    folder: "02 andrea bertin playa",
    location: "Costa Central",
    year: "2020",
    type: "Residencial Costero",
    description: "Entre el viento marino y la arena, este jardín costero fue diseñado para resistir y florecer. Plantas tolerantes a la sal, texturas naturales y un diseño que abraza el paisaje en lugar de ignorarlo.",
  },
  "antumalal": {
    name: "Jardín Antumalal",
    folder: "02 JARDIN ANTUMALAL",
    location: "Pucón",
    year: "2017",
    type: "Hotelería",
    description: "El Hotel Antumalal asoma sobre el lago Villarrica con una arquitectura de los años cincuenta que dialoga con la naturaleza patagónica. El jardín refuerza esa conversación: nativo, rugoso, horizontal. Un paisaje que no interrumpe la vista sino que la enmarca.",
  },
  "gracia-cariola": {
    name: "Jardín Gracia Cariola",
    folder: "02 JARDIN GRACIA CARIOLA",
    location: "Santiago",
    year: "2016",
    type: "Residencial",
    description: "Jardín de escala íntima en el sector oriente de Santiago. La intervención mantiene la privacidad con setos estructurados y abre el espacio hacia un patio central donde una higuera antigua marca el tiempo.",
  },
  "los-vilos": {
    name: "Jardín Los Vilos",
    folder: "02 JARDIN LOS VILOS",
    location: "Los Vilos",
    year: "2021",
    type: "Residencial Costero",
    description: "En la costa norte chica, donde el clima es árido y el viento constante, este jardín demuestra que la belleza no requiere agua abundante. Suculentas, lavandas y gramíneas construyen un paisaje austero y poderoso frente al Pacífico.",
  },
  "ranco": {
    name: "Jardín Ranco",
    folder: "02 JARDIN RANCO",
    location: "Lago Ranco",
    year: "2022",
    type: "Residencial Lacustre",
    description: "A orillas del lago Ranco, rodeado de bosque nativo valdiviano. El jardín no busca imponerse sino pertenecer — especies nativas del sur, piedra local y caminos que invitan a perderse entre los árboles.",
  },
  "sennerman": {
    name: "Jardín Sennerman",
    folder: "02 JARDIN SENNERMAN",
    location: "Santiago",
    year: "2020",
    type: "Residencial",
    description: "Un jardín diseñado para ser visto desde adentro y habitado desde afuera. Volúmenes de boj estructuran el espacio y enmarcan vistas hacia el cerro. La piscina aparece como espejo en el centro de la composición.",
  },
  "denisse-neger": {
    name: "Denisse Neger",
    folder: "02 Denisse Neger",
    location: "Santiago",
    year: "2015",
    type: "Residencial",
    description: "Proyecto residencial en el sector alto de Santiago. El jardín integra distintos niveles con escaleras de piedra y vegetación abundante, creando rincones de descanso en cada plataforma.",
  },
  "lidia-langlois": {
    name: "Lidia Langlois",
    folder: "02 Lidia Langlois",
    location: "Santiago",
    year: "2014",
    type: "Residencial",
    description: "Un jardín que ha madurado con el tiempo. Las fotografías capturan el proyecto en distintas estaciones, mostrando cómo una buena estructura vegetal permite que el jardín evolucione con gracia año tras año.",
  },
  "maria-gracia": {
    name: "María Gracia",
    folder: "02 Maria Gracia",
    location: "Santiago",
    year: "2018",
    type: "Residencial",
    description: "Jardín residencial diseñado en torno a un árbol centenario preexistente. Toda la intervención respeta y celebra esa presencia: los caminos lo rodean, las plantas lo acompañan, la terraza lo protege.",
  },
  "china-correa": {
    name: "China Correa",
    folder: "02 china correa",
    location: "Santiago",
    year: "2017",
    type: "Residencial",
    description: "Un jardín compacto con mucho carácter. La escasez de espacio se convierte en virtud: cada planta fue elegida con criterio y cada rincón tiene propósito. El resultado es denso, fragante y siempre cambiante.",
  },
  "falabella": {
    name: "Falabella",
    folder: "02 falabella",
    location: "Santiago",
    year: "2016",
    type: "Corporativo",
    description: "Proyecto de paisajismo corporativo para las oficinas centrales de Falabella. Jardines interiores y exteriores que mejoran el bienestar de las personas y refuerzan la identidad de marca a través del paisaje.",
  },
  "jose": {
    name: "José",
    folder: "02 jose",
    location: "Santiago",
    year: "2019",
    type: "Residencial",
    description: "Jardín de diseño contemporáneo con materialidad noble. Piedra, madera y vegetación de paleta reducida pero impactante. La geometría limpia contrasta con la exuberancia de las plantas.",
  },
  "khammis": {
    name: "Khammis",
    folder: "02 khammis",
    location: "Santiago",
    year: "2021",
    type: "Residencial",
    description: "Proyecto residencial con fuerte presencia de agua. Un estanque lineal recorre el jardín creando reflejo y sonido, transformando el exterior en un espacio de calma y contemplación.",
  },
  "la-plaza": {
    name: "La Plaza",
    folder: "02 la plaza",
    location: "Santiago",
    year: "2018",
    type: "Residencial",
    description: "El nombre lo dice todo: un jardín que funciona como plaza. Árboles que dan sombra, pavimento que invita a caminar, plantas que dan color. Un espacio público en escala doméstica.",
  },
  "mellafe": {
    name: "Mellafe",
    folder: "02 mellafe",
    location: "Santiago",
    year: "2020",
    type: "Residencial",
    description: "Proyecto de jardín y terraza en el barrio de Mellafe. La intervención conecta los distintos niveles de la vivienda con vegetación continua, haciendo del recorrido vertical una experiencia paisajística.",
  },
  "moira": {
    name: "Moira",
    folder: "02 moira",
    location: "Santiago",
    year: "2019",
    type: "Residencial",
    description: "Jardín diseñado en estrecha colaboración con la arquitectura interior. Las plantas elegidas complementan los materiales de la construcción: tonos cálidos, texturas naturales y una paleta que prolonga el interior hacia afuera.",
  },
  "pilar": {
    name: "Pilar",
    folder: "02 pilar",
    location: "Santiago",
    year: "2016",
    type: "Residencial",
    description: "Un jardín maduro que acumula historia. Los árboles plantados hace años ya dan sombra, los arbustos han tomado forma y los caminos se han asentado en el suelo. Un proyecto que demuestra qué significa diseñar para el tiempo.",
  },
  "security": {
    name: "Security",
    folder: "02 security",
    location: "Santiago",
    year: "2017",
    type: "Corporativo",
    description: "Paisajismo para el edificio corporativo del Banco Security. Jardines de representación que equilibran la escala institucional con la calidez de lo natural, creando un ambiente de confianza y bienestar.",
  },
  "los-vilos-02": {
    name: "Los Vilos",
    folder: "02 los vilos",
    location: "Los Vilos",
    year: "2021",
    type: "Residencial Costero",
    description: "Segunda intervención en la costa de Los Vilos, con una escala mayor y un vocabulario más audaz. El jardín dialoga directamente con el océano: plantas que soportan la sal, formas que acompañan el viento.",
  },

  // ── Resto ──────────────────────────────────────────────────────────────────
  "alejandra-prieto": {
    name: "Alejandra Prieto",
    folder: "Alejandra Prieto",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín residencial diseñado en torno a la vida familiar. Espacios diferenciados para el juego, el descanso y el encuentro, todos conectados por una paleta vegetal coherente y abundante.",
  },
  "alejandro-alvarez": {
    name: "Alejandro Álvarez",
    folder: "Alejandro Alvarez",
    location: "Santiago",
    type: "Residencial",
    description: "Proyecto de diseño exterior con énfasis en la estructura. Setos formales, árboles de alineación y un eje central que organiza el espacio y crea profundidad visual desde la entrada principal.",
  },
  "ana-maria-figueroa": {
    name: "Ana María Figueroa",
    folder: "Ana Maria Figueroa",
    location: "Santiago",
    type: "Residencial",
    description: "Un jardín íntimo pensado para ser disfrutado en silencio. Plantas aromáticas, rincones sombreados y una fuente de agua que acompaña el día con su sonido constante.",
  },
  "andrea-bertin": {
    name: "Andrea Bertin",
    folder: "Andrea Bertin",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín tradicional con vocación contemporánea. La estructura clásica — bordes definidos, árboles de sombra, zona de pasto — se actualiza con una paleta vegetal más atrevida y materiales nobles.",
  },
  "carola-matta": {
    name: "Carola Matta",
    folder: "Carola Matta",
    location: "Santiago",
    type: "Residencial",
    description: "El jardín de Carola Matta nace de una conversación larga sobre cómo quería vivir su exterior. El resultado es personal e irreplicable: una combinación de plantas que refleja exactamente el gusto y la forma de vida de quien lo habita.",
  },
  "carola-del-campo": {
    name: "Carola del Campo",
    folder: "Carola del Campo",
    location: "Santiago",
    type: "Residencial",
    description: "Proyecto de remodelación de jardín existente. La intervención respeta lo que ya estaba — árboles maduros, muros de piedra — y agrega una nueva capa de diseño que actualiza el espacio sin borrarlo.",
  },
  "carolina-velasco": {
    name: "Carolina Velasco",
    folder: "Carolina Velasco",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín de color. La paleta vegetal fue elegida para generar impacto visual durante todo el año: floraciones escalonadas, follajes contrastantes y estructuras perennes que sostienen el conjunto.",
  },
  "cecilia-claro": {
    name: "Cecilia Claro",
    folder: "Cecilia Claro",
    location: "Santiago",
    type: "Residencial",
    description: "Una intervención delicada en un jardín con historia. Los árboles antiguos dictaron el diseño: todo lo nuevo se pensó en relación a sus copas, sus raíces y sus sombras.",
  },
  "clinica-lo-curro": {
    name: "Clínica Lo Curro",
    folder: "Clinica Lo Curro",
    location: "Santiago",
    type: "Salud",
    description: "El paisajismo de una clínica tiene una responsabilidad especial: crear espacios que contribuyan a la recuperación de las personas. Plantas con propiedades calmantes, jardines accesibles y visuales que conectan el interior con la naturaleza.",
  },
  "diego-abadie": {
    name: "Diego Abadie",
    folder: "Diego Abadie",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín urbano diseñado para maximizar el verde en un espacio compacto. Muros vegetales, especies de bajo mantenimiento y una terraza de madera que amplía visualmente el interior hacia afuera.",
  },
  "eleana-vidaurre": {
    name: "Eleana Vidaurre",
    folder: "Eleana Vidaurre",
    location: "Santiago",
    type: "Residencial",
    description: "Un jardín que cambia según la hora y la estación. La elección de plantas considera la luz a distintos momentos del día, creando un espacio siempre vivo y siempre distinto.",
  },
  "fernanda-otero": {
    name: "Fernanda Otero",
    folder: "Fernanda Otero",
    location: "Santiago",
    type: "Residencial",
    description: "Proyecto residencial con énfasis en el bienestar. Zona de huerto, jardín de flores para cortar y áreas de descanso entre vegetación abundante: un exterior diseñado para ser usado todos los días.",
  },
  "francisca-goycolea": {
    name: "Francisca Goycolea",
    folder: "Francisca Goycolea",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín de herencia clásica actualizado con sensibilidad contemporánea. Los rosales y arbustos perennes conviven con gramíneas y plantas de textura, creando un contraste que se siente natural.",
  },
  "jael-ergas": {
    name: "Jael Ergas",
    folder: "Jael Ergas",
    location: "Santiago",
    type: "Residencial",
    description: "Una de las intervenciones más completas del estudio: diseño de jardín, iluminación, riego y mantenimiento integral. Un proyecto que acompaña a sus habitantes durante años.",
  },
  "josefa-garcia": {
    name: "Josefa García de la Huerta",
    folder: "Josefa Garcia de la Huerta",
    location: "Santiago",
    type: "Residencial",
    description: "El jardín como extensión del salón. Los espacios exteriores fueron diseñados para recibir, para compartir, para estar. Una paleta cálida de plantas y materiales prolonga la calidez del interior hacia afuera.",
  },
  "josefina-passalacqua": {
    name: "Josefina Passalacqua",
    folder: "Josefina Passalacqua",
    location: "Santiago",
    type: "Residencial",
    description: "Proyecto personal con todo el cuidado que eso implica. El jardín de Josefina Passalacqua reúne las especies favoritas, las memorias de infancia y las intuiciones acumuladas en años de trabajo con el paisaje.",
  },
  "juan-irrarazabal": {
    name: "Juan E. Irarrázabal",
    folder: "Juan E Irrarazabal",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín de gran escala en el sector oriente de Santiago. La composición maneja distintos planos de profundidad: un primer plano florido, una zona media estructurada y un fondo de árboles que cierra el espacio.",
  },
  "m-elisa-sotta": {
    name: "M. Elisa Sotta",
    folder: "M.Elisa Sotta",
    location: "Santiago",
    type: "Residencial",
    description: "Un jardín diseñado para crecer con la familia. Los espacios evolucionan según las necesidades — primero una zona de juego, luego un jardín de contemplación — sin perder la coherencia del proyecto original.",
  },
  "monica-valdes": {
    name: "Mónica Valdés",
    folder: "Monica Valdes",
    location: "Santiago",
    type: "Residencial",
    description: "Proyecto en un terreno con fuerte pendiente que se convierte en oportunidad de diseño. Las plataformas escalonadas crean distintos ambientes, cada uno con su propio carácter y su propia vista.",
  },
  "paula-delano": {
    name: "Paula Delano",
    folder: "Paula Delano",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín pensado desde la infancia. Los rincones para explorar, los árboles para trepar y los caminos sinuosos responden a la escala de los niños, sin perder la elegancia que los adultos también necesitan.",
  },
  "pollo-mir": {
    name: "Pollo Mir",
    folder: "Pollo Mir",
    location: "Santiago",
    type: "Residencial",
    description: "Una intervención que toma riesgos y los resuelve con gracia. La combinación de especies poco convencionales, materialidades brutas y formas orgánicas produce un jardín con carácter propio y difícil de olvidar.",
  },
  "rosario-figueroa": {
    name: "Rosario Figueroa",
    folder: "Rosario Figueroa",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín mediterráneo adaptado al clima de Santiago. Lavandas, romeros, olivos y cipreses crean una atmósfera cálida y aromática que evoca el sur de Europa sin abandonar lo local.",
  },
  "sebastian-oddo": {
    name: "Sebastián Oddo",
    folder: "Sebastian Oddo",
    location: "Santiago",
    type: "Residencial",
    description: "Diseño de exteriores con énfasis en los espacios nocturnos. La iluminación fue parte integral del proyecto desde el inicio: el jardín se transforma al caer la noche en un espacio completamente distinto, igualmente bello.",
  },
  "titi-marincovic": {
    name: "Titi Marincovic",
    folder: "Titi Marincovic",
    location: "Santiago",
    type: "Residencial",
    description: "Un jardín generoso, lleno de plantas y lleno de vida. La abundancia no es desorden: detrás de la exuberancia hay una estructura clara que organiza el espacio y lo hace habitable en todas las estaciones.",
  },
  "vespucio-2700": {
    name: "Vespucio 2700",
    folder: "VESPUCIO 2700",
    subfolder: "Web Res",
    location: "Santiago",
    year: "2021",
    type: "Corporativo",
    description: "Proyecto de paisajismo urbano en la avenida Vespucio. Un edificio corporativo de nueva generación que integra el verde como parte constitutiva de su arquitectura: jardines en acceso, patios interiores y terrazas ajardinadas en distintos niveles.",
  },
  "veronica-calderon": {
    name: "Verónica Calderón",
    folder: "Veronica Calderon",
    location: "Santiago",
    type: "Residencial",
    description: "Jardín diseñado para una casa que recientemente cambió de propietaria. La intervención transforma el espacio respetando lo que ya existía y añadiendo una nueva capa de diseño que lo hace propio.",
  },
  "ximena-campos": {
    name: "Ximena Campos",
    folder: "Ximena Campos",
    location: "Santiago",
    type: "Residencial",
    description: "Un exterior íntimo diseñado para el descanso. Sombra generosa, plantas fragantes y una paleta de colores suaves crean un jardín donde el tiempo pasa diferente.",
  },
  "angelica-correa": {
    name: "Angélica Correa",
    folder: "angelica correa",
    location: "Santiago",
    type: "Residencial",
    description: "Proyecto de pequeña escala con gran precisión. Cada planta fue elegida por su textura, color y comportamiento estacional. Un jardín que recompensa la atención al detalle.",
  },
  "cimm": {
    name: "CIMM",
    folder: "cimm",
    location: "Santiago",
    year: "2018",
    type: "Corporativo",
    description: "Paisajismo para el Centro de Investigación Minera y Metalúrgica. Jardines que acompañan los espacios de trabajo e investigación, integrando naturaleza en un entorno técnico de alta exigencia.",
  },
  "saval": {
    name: "Saval",
    folder: "saval",
    location: "Santiago",
    type: "Corporativo",
    description: "Proyecto de exteriores para las instalaciones de Saval. El diseño considera la escala industrial del entorno y crea zonas verdes que humanizan el espacio y mejoran la experiencia de quienes trabajan ahí.",
  },
  "verdecee": {
    name: "Verdecee",
    folder: "verdecee",
    location: "Santiago",
    type: "Residencial",
    description: "Un jardín urbano en altura. La terraza se transforma en un oasis sobre la ciudad: jardines de bajo mantenimiento, especies resistentes al viento y una composición que maximiza el verde en cada metro cuadrado disponible.",
  },
};
